Executable = dummy_2017.sh
Universe = vanilla
use_x509userproxy = true
Should_Transfer_Files = YES
Transfer_Output_Files = ""
Transfer_Input_Files = step1_cfg.py,step2_cfg.py,step3_cfg.py,step4_cfg.py,step5_cfg.py,step6_cfg.py, step7_cfg.py,step_1_LO_cfg.py
+JobFlavour = "tomorrow"
Output      = logs_2017_noEFTDecay/log_$(Cluster)_$(Process).stdout
Error       = logs_2017_noEFTDecay/log_$(Cluster)_$(Process).stdout
Log         = logs_2017_noEFTDecay/log_$(Cluster)_$(Process).log
MY.SingularityImage = "/cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-cat/cmssw-lxplus/cmssw-el7-lxplus:latest/"

Arguments   =  $(ClusterId) $(ProcId)  WWToLNuJJ_01j_LO_SMEFTsim_noEFTDecay_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2017/WWToLNuJJ_01j_LO_SMEFTsim_noEFTDecay initrwgt_aQGC16_smeft.header
Queue 2500
Arguments   =  $(ClusterId) $(ProcId)   WZToLNujj_01j_LO_SMEFTsim_noEFTDecay_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz   /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2017/WZToLNuJJ_01j_LO_SMEFTsim_noEFTDecay initrwgt_aQGC16_smeft.header
Queue 2500
#Arguments   =  $(ClusterId) $(ProcId) WZToLNuJJ_01j_LO_EWdim6NLO_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2017/WZToLNuJJ_01j_LO_EWdim6NLO initrwgt_aQGC16.header
#Queue 1000
#Arguments   =  $(ClusterId) $(ProcId) WWToLNuJJ_01j_LO_EWdim6NLO_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz	/eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2017/WWToLNuJJ_01j_LO_EWdim6NLO initrwgt_aQGC16.header
#Queue 2000
