Executable = dummy_2016_prevfp.sh
Universe = vanilla
use_x509userproxy = true
Transfer_Output_Files = ""
Should_Transfer_Files = YES
Transfer_Input_Files = step_1_prevfp_cfg.py,step_2_prevfp_cfg.py,step_3_prevfp_cfg.py,step_4_prevfp_cfg.py,step_5_prevfp_cfg.py,step_6_prevfp_cfg.py,step_7_prevfp_cfg.py,step_1_prevfp_LO_cfg.py
+JobFlavour = "tomorrow"
Output      = logs_2016pre_EFTDim6_HTBins/log_prevfp_$(Cluster)_$(Process).stdout
Error       = logs_2016pre_EFTDim6_HTBins/log_prevfp_$(Cluster)_$(Process).stdout
Log         = logs_2016pre_EFTDim6_HTBins/log_prevfp_$(Cluster)_$(Process).log
MY.SingularityImage = "/cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-cat/cmssw-lxplus/cmssw-el7-lxplus:latest/"

#Arguments   =  $(ClusterId) $(ProcId) WVToLNuJJ_01j_LO_SMEFTsim_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2016preVFP/WVToLNuJJ_01j_LO_SMEFTsim_noEFTDecay   initrwgt_smeft_wv_corr.header
#Queue 5000

Arguments   =  $(ClusterId) $(ProcId) WVToLNuJJ_01j_LO_SMEFTsim_HT0To1000_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2016preVFP/WVToLNuJJ_01j_LO_SMEFTsim_HT0To1000   initrwgt_smeft_wv_corr.header
Queue 1000
Arguments   =  $(ClusterId) $(ProcId) WVToLNuJJ_01j_LO_SMEFTsim_HT1000To2000_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2016preVFP/WVToLNuJJ_01j_LO_SMEFTsim_HT1000To2000   initrwgt_smeft_wv_corr.header
Queue 3000
Arguments   =  $(ClusterId) $(ProcId) WVToLNuJJ_01j_LO_SMEFTsim_HT2000ToInf_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2016preVFP/WVToLNuJJ_01j_LO_SMEFTsim_HT2000ToInf   initrwgt_smeft_wv_corr.header
Queue 7000


#Arguments   =  $(ClusterId) $(ProcId) WWToLNuJJ_01j_LO_EWdim6NLO_HT0To1000_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2016preVFP/WWToLNuJJ_01j_LO_EWdim6NLO_HT0To1000   initrwgt_aQGC16.header
#Queue 100
#Arguments   =  $(ClusterId) $(ProcId) WWToLNuJJ_01j_LO_EWdim6NLO_HT1000To2000_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2016preVFP/WWToLNuJJ_01j_LO_EWdim6NLO_HT1000To2000 initrwgt_aQGC16.header
#Queue 1000
#Arguments   =  $(ClusterId) $(ProcId) WWToLNuJJ_01j_LO_EWdim6NLO_HT2000ToInf_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2016preVFP/WWToLNuJJ_01j_LO_EWdim6NLO_HT2000ToInf initrwgt_aQGC16.header
#Queue 2000
#Arguments   =  $(ClusterId) $(ProcId) WZToLNuJJ_01j_LO_EWdim6NLO_HT0To1000_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2016preVFP/WZToLNuJJ_01j_LO_EWdim6NLO_HT0To1000    initrwgt_aQGC16.header
#Queue 100
#Arguments   =  $(ClusterId) $(ProcId) WZToLNuJJ_01j_LO_EWdim6NLO_HT1000To2000_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2016preVFP/WZToLNuJJ_01j_LO_EWdim6NLO_HT1000To2000  initrwgt_aQGC16.header
#Queue 1000
#Arguments   =  $(ClusterId) $(ProcId) WZToLNuJJ_01j_LO_EWdim6NLO_HT2000ToInf_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2016preVFP/WZToLNuJJ_01j_LO_EWdim6NLO_HT2000ToInf   initrwgt_aQGC16.header
#Queue 2000
