Executable = dummy_2016_prevfp.sh
Universe = vanilla
use_x509userproxy = true
transfer_output_files = ""
Should_Transfer_Files = YES
Transfer_Input_Files = step_1_prevfp_cfg.py,step_2_prevfp_cfg.py,step_3_prevfp_cfg.py,step_4_prevfp_cfg.py,step_5_prevfp_cfg.py,step_6_prevfp_cfg.py,step_7_prevfp_cfg.py,step_1_prevfp_LO_cfg.py
+JobFlavour = "tomorrow"
Output      = jobs/log_prevfp_$(Cluster)_$(Process).log
Error       = jobs/log_prevfp_$(Cluster)_$(Process).log
Log         = jobs/log_prevfp_$(Cluster)_$(Process).log
MY.SingularityImage = "/cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-cat/cmssw-lxplus/cmssw-el7-lxplus:latest/"

Arguments   =  $(ClusterId) $(ProcId) WpWmToLpNujj_01j_LO_SMEFT_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz  /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2016preVFP/WWToLNujj_01j_SMEFT_LO
Queue 2500
Arguments   =  $(ClusterId) $(ProcId) WZToLNujj_01j_LO_SMEFT_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz  /eos/user/r/rasharma/post_doc_ihep/aTGC/SMEFT_samples/2016preVFP/WZToLNujj_01j_SMEFT_LO
Queue 2500

