Executable = dummy_2016_prevfp.sh
Universe = vanilla
use_x509userproxy = true
Should_Transfer_Files = YES
Transfer_Input_Files = step_1_prevfp_cfg.py,step_2_prevfp_cfg.py,step_3_prevfp_cfg.py,step_4_prevfp_cfg.py,step_5_prevfp_cfg.py,step_6_prevfp_cfg.py,step_7_prevfp_cfg.py,step_1_prevfp_LO_cfg.py
+JobFlavour = "tomorrow"
Output      = jobs/log_prevfp_$(Cluster)_$(Process).log
Error       = jobs/log_prevfp_$(Cluster)_$(Process).log
Log         = jobs/log_prevfp_$(Cluster)_$(Process).log
transfer_output_files = "" 
should_transfer_files = YES
MY.SingularityImage = "/cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-cat/cmssw-lxplus/cmssw-el7-lxplus:latest/"
+AccountingGroup = "group_u_CMST3.all"

Arguments   =  $(ClusterId) $(ProcId) WpWmToLpNujj_01j_LO_SMEFT_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz  /eos/cms/store/cmst3/group/dpsww/SMEFT_samples/2016preVFP/WWToLNujj_01j_SMEFT_LO
Queue 500
Arguments   =  $(ClusterId) $(ProcId) WZToLNujj_01j_LO_SMEFT_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz  /eos/cms/store/cmst3/group/dpsww/SMEFT_samples/2016preVFP/WZToLNujj_01j_SMEFT_LO
Queue 500


##am#Arguments   =  $(ClusterId) $(ProcId) WpWmToLpNujj_01j_aTGC_pTW-150toInf_mWV-800toInf_4f_NLO_FXFX_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz  /eos/cms/store/group/phys_smp/ec/anmehta/aTGC_Apr2024_UL16preVFP/WpWmToLpNujj_01j_aTGC_pTW-150toInf_mWV-800toInf_4f_NLO_FXFX
##am#queue 1200
##am
##amArguments   =  $(ClusterId) $(ProcId) WmWpToLmNujj_01j_aTGC_pTW-150toInf_mWV-800toInf_4f_NLO_FXFX_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz  /eos/cms/store/group/phys_smp/ec/anmehta/aTGC_Apr2024_UL16preVFP/WmWpToLmNujj_01j_aTGC_pTW-150toInf_mWV-800toInf_4f_NLO_FXFX
##amqueue 1200 
##am
##am#Arguments   =  $(ClusterId) $(ProcId) WpWmToLpNujj_01j_aTGC_pTW-150toInf_mWV-600to800_4f_NLO_FXFX_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz  /eos/cms/store/group/phys_smp/ec/anmehta/aTGC_Apr2024_UL16preVFP/WpWmToLpNujj_01j_aTGC_pTW-150toInf_mWV-600to800_4f_NLO_FXFX
##am#queue 800 
##am
##am#Arguments   =  $(ClusterId) $(ProcId) WmWpToLmNujj_01j_aTGC_pTW-150toInf_mWV-150to600_4f_NLO_FXFX_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz  /eos/cms/store/group/phys_smp/ec/anmehta/aTGC_Apr2024_UL16preVFP/WmWpToLmNujj_01j_aTGC_pTW-150toInf_mWV-150to600_4f_NLO_FXFX
##am#queue 600 
##am#Arguments   =  $(ClusterId) $(ProcId) WmZToLmNujj_01j_aTGC_pTZ-150toInf_mWV-150to600_4f_NLO_FXFX_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/cms/store/group/phys_smp/ec/anmehta/aTGC_Apr2024_UL16preVFP/WmZToLmNujj_01j_aTGC_pTZ-150toInf_mWV-150to600_4f_NLO_FXFX
##am#queue 600
##am
##am#Arguments   =  $(ClusterId) $(ProcId) WmWpToLmNujj_01j_aTGC_pTW-150toInf_mWV-600to800_4f_NLO_FXFX_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz  /eos/cms/store/group/phys_smp/ec/anmehta/aTGC_Apr2024_UL16preVFP/WmWpToLmNujj_01j_aTGC_pTW-150toInf_mWV-600to800_4f_NLO_FXFX
##am#queue 800
##am#Arguments   =  $(ClusterId) $(ProcId) WpWmToLpNujj_01j_aTGC_pTW-150toInf_mWV-150to600_4f_NLO_FXFX_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz  /eos/cms/store/group/phys_smp/ec/anmehta/aTGC_Apr2024_UL16preVFP/WpWmToLpNujj_01j_aTGC_pTW-150toInf_mWV-150to600_4f_NLO_FXFX
##am#queue 600 
##am
##am
##am
##am
##am#Arguments   =  $(ClusterId) $(ProcId) WmZToLmNujj_01j_aTGC_pTZ-150toInf_mWV-800toInf_4f_NLO_FXFX_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/cms/store/group/phys_smp/ec/anmehta/aTGC_Apr2024_UL16preVFP/WmZToLmNujj_01j_aTGC_pTZ-150toInf_mWV-800toInf_4f_NLO_FXFX
##am#queue 1200
##am#Arguments   =  $(ClusterId) $(ProcId) WmZToLmNujj_01j_aTGC_pTZ-150toInf_mWV-600to800_4f_NLO_FXFX_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/cms/store/group/phys_smp/ec/anmehta/aTGC_Apr2024_UL16preVFP/WmZToLmNujj_01j_aTGC_pTZ-150toInf_mWV-600to800_4f_NLO_FXFX
##am#queue 800 
##am#Arguments   =  $(ClusterId) $(ProcId) WpZToLpNujj_01j_aTGC_pTZ-150toInf_mWV-150to600_4f_NLO_FXFX_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/cms/store/group/phys_smp/ec/anmehta/aTGC_Apr2024_UL16preVFP/WpZToLpNujj_01j_aTGC_pTZ-150toInf_mWV-150to600_4f_NLO_FXFX
##am#queue  600
##am#Arguments   =  $(ClusterId) $(ProcId) WpZToLpNujj_01j_aTGC_pTZ-150toInf_mWV-600to800_4f_NLO_FXFX_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/cms/store/group/phys_smp/ec/anmehta/aTGC_Apr2024_UL16preVFP/WpZToLpNujj_01j_aTGC_pTZ-150toInf_mWV-600to800_4f_NLO_FXFX
##am#queue 800
##am#Arguments   =  $(ClusterId) $(ProcId) WpZToLpNujj_01j_aTGC_pTZ-150toInf_mWV-800toInf_4f_NLO_FXFX_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz /eos/cms/store/group/phys_smp/ec/anmehta/aTGC_Apr2024_UL16preVFP/WpZToLpNujj_01j_aTGC_pTZ-150toInf_mWV-800toInf_4f_NLO_FXFX
##am#queue 1200
